version: "3.0"

volumes:
  db-data:
    external: false

services:

  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}

  app:
    build: .
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      OCPP_ADMIN_USER: ${OCPP_ADMIN_USER:-admin}
      OCPP_ADMIN_PASSWORD: ${OCPP_ADMIN_PASSWORD:-1234}
      OCPP_WEBAPI_KEY: ${OCPP_WEBAPI_KEY:-STEVE-API-KEY}
      OCPP_WEBAPI_VALUE: ${OCPP_WEBAPI_VALUE:-asdf}
      OCPP_SERVER_IP: ${OCPP_SERVER_IP:-0.0.0.0}
    links:
      - "db:mariadb"
    ports:
      - "8180:8180"
    depends_on:
      - db
